### ISSUE TITLE
[Room History] Hide useless messages on new room creation

### ISSUE THREAD

**Issue by giomfo** [dinsic-pim/riot-web#134]
Currently on Tchap-web, the following messages are displayed on each new forum:
![image](https://user-images.githubusercontent.com/8969772/103538482-906c2700-4e96-11eb-99be-84d07a55f5b4.png)

Most of them are useless, we should hide them

"... a empêché les invités de rejoindre le salon." is misunderstood by the users, it is about the unsupported guest access and not the actual invite mechanism

The same remark must be considered for the private rooms too

**Comment by Yoshiin** [comment]
We decided to hide `aliases`, `topic`, `history_visibility`, `encryption`, `pinned_events`, `server_acl`, `tombstone`, `guest_access`, `related_groups`.

The `join_rules` will be updated from "(...) a rendu le salon public à tous ceux qui en connaissent le lien." to "(...) a rendu le salon accessible à tous ceux qui en connaissent le lien.".

**Comment by Yoshiin** [comment]
`canonical_alias` was added to the hidden list.
