### ISSUE TITLE
[Global] Update mobile_guide encoding

### ISSUE THREAD

**Issue by Yoshiin** [dinsic-pim/riot-web#142]
Update mobile_guide html encoding.

**Comment by Nivann** [comment]
# Mauvais affichage sur la version Web OS de la page de téléchargement. 
## Plusieurs mots apparaissent brouillés, ce qui nuit à l'aspect général et à l'accessibilité de la page. 

https://www.tchap.gouv.fr/mobile_guide/

![IMG_5295 (1)](https://user-images.githubusercontent.com/99986548/155309958-ef9abe06-3cce-4ce6-9191-c2c983e676c4.jpg)
![IMG_5296 (1)](https://user-images.githubusercontent.com/99986548/155309981-9512b4c5-b4b7-4252-b0c8-20021bc90cc5.jpg)
