### ISSUE TITLE
I have a question regarding blocking unofficial apps, did you do this on tchap?

### ISSUE THREAD

**Issue by chagai95** [dinsic-pim/riot-web#148]
Is it possible to login from a different matrix client?

Also, are you planning on open sourcing synapse?

Would love to chat with you @Yoshiin where is best for you? https://chagai.website or @me:chagai.website

**Comment by jdauphant** [comment]
Hello @chagai95, there is no blocking of unofficial apps.
Synapse is already open source : https://github.com/matrix-org/synapse-dinsic
