### ISSUE TITLE
Mettre à jour le lien de la FAQ dans Tchap Web

### ISSUE THREAD

**Issue by JDixmier** [dinsic-pim/riot-web#159]
Nouveau lien : https://tchap.beta.gouv.fr/faq

**Comment by estellecomment** [comment]
On a mis une redirection, de https://tchap.beta.gouv.fr/faq (ancien) vers https://tchap.beta.gouv.fr/faq (nouveau)

La vieille FAQ est pour le moment sur https://www.tchap.gouv.fr/faq-old/

**Comment by estellecomment** [comment]
Certains liens vers des paragraphes spécifiques de l'ancienne FAQ ont du être changés.

```
        "encryption_info": "/faq/#tcq05_001",
        "export_info": "/faq/#tcq03_002",
        "mobile_info": "/faq/#tcq06_002",
        "browser_session_info": "/faq/#tcq03_002",
```

Deux liens nécessitent un changement de la nouvelle page de FAQ pour etre cohérents : 
browser_session_info : Disable automatic logout on your browser / Désactivez la déconnexion automatique de votre navigateur 
export_info : Export your encryption keys / Exporter vos clés de chiffrement

**Comment by estellecomment** [comment]
opened https://github.com/tchapgouv/tchap-landing-page/issues/59

**Comment by estellecomment** [comment]
Je fais une PR pour mettre à jour la config.json, pour refleter les changements faits en prod.

**Comment by estellecomment** [comment]
PR https://github.com/tchapgouv/tchap-web/pull/164

**Comment by estellecomment** [comment]
done
