### ISSUE TITLE
Avatar's image not displaying correctly on room members'card

### ISSUE THREAD

**Issue by clemhacks** [dinsic-pim/riot-web#160]
<img width="214" alt="bug avatar" src="https://user-images.githubusercontent.com/61703515/148404997-fd4dc06a-9bc8-41ee-bc0f-19d0d2f8335e.PNG">

Browser version : Chrome 96.0.4664.110
Tchap Web version : 2.3.7

**Comment by estellecomment** [comment]
Duplicate of https://github.com/tchapgouv/tchap-web/issues/191, closing this one.
