### ISSUE TITLE
Mettre à jour CGU

### ISSUE THREAD

**Issue by clemhacks** [dinsic-pim/riot-web#161]
Au sein de l'app web avec redirection possible vers landing page si plus simple

**Comment by jdauphant** [comment]
Fait en prod

**Comment by clemhacks** [comment]
Je ne vois pas les nouvelles cgu en prod

**Comment by jdauphant** [comment]
j'ai lu un peut rapidement, c'est la FAQ qui est redirigé.
Par contre, les CGUs vont être sur le projet landing page. 
Et pour le lien de CGU à corriger, c'est à mettre sur le projet d'infra.

**Comment by jdauphant** [comment]
Done
