### ISSUE TITLE
Adapt text of the welcome popup (appearing after signing in)

### ISSUE THREAD

**Issue by clemhacks** [dinsic-pim/riot-web#163]
<img width="602" alt="02 screen" src="https://user-images.githubusercontent.com/61703515/149307958-f774c992-bc66-419a-87ff-7caab5b41a40.PNG">

Suggestion : 
Tchap c'est la messagerie instantanée de l'Administration, conçue pour les agents des trois fonctions publiques, pour communiquer facilement en toute sécurité.
Les échanges privés sont chiffrés de bout en bout et lisibles grâce à vos clés de chiffrement stockées sur vos appareils (en savoir plus ici).
Pour une expérience optimale, veuillez à rester toujours rester connecté.e, voici comment faire : 
...

**Comment by estellecomment** [comment]
Je vais fermer cette issue, parce que je crois que @Caroline-lawson et @JDixmier veulent complètement supprimer ce dialog de toutes facons, ou au moins changer le texte.
(rouvrez l'issue si je me trompe)
