### ISSUE TITLE
Add visibility for edit and reactions

### ISSUE THREAD

**Issue by jdauphant** [dinsic-pim/riot-web#166]
## Goal

Try the fastest way to get reactions and edits in v2. 
Note : Just seeing them (not creating them) can be enough to support the android tatin compatibility. If it's faster, disable the creation.

## History 

Tchap web is based on element/riot from 23 april 2019 : https://github.com/tchapgouv/matrix-react-sdk/commits/develop?after=a1ab719f25a6dddec2b7f1112c436cebcb13fe4f+384&branch=develop

Les reactions semblent avoir été implémenté le 30 avril 2019 : https://github.com/matrix-org/matrix-react-sdk/pull/2937 et amélioré le 2 mai : https://github.com/matrix-org/matrix-react-sdk/pull/2940
l'ajout de l'édition de message a été fait le 9 mai : https://github.com/matrix-org/matrix-react-sdk/pull/2952 puis amélioré tous le mois de mai : https://github.com/matrix-org/matrix-react-sdk/search?p=3&q=message+editing&type=issues

**Comment by giomfo** [comment]
done partially by https://github.com/tchapgouv/matrix-react-sdk/pull/370

**Comment by estellecomment** [comment]
This is done by https://github.com/tchapgouv/matrix-react-sdk/pull/370 and will be released in 2.4.0.
Closing this in favor of the ticket for 2.4.0 : #180
