### ISSUE TITLE
Masquer les reactions et edits avant de mettre en prod

### ISSUE THREAD

**Issue by estellecomment** [dinsic-pim/riot-web#181]
Epic : #180 

Methode pour masquer les reactions et edits pour le moment, et les remettre facilement quand on les deploiera sur tous les clients.
Most likely, just disable dans config.json. Tester que ca marche bien.

**Comment by celiacheff** [comment]
Je confirme pour setter à "disable" dans le config.json (les supprimer fonctionne aussi)

**Comment by estellecomment** [comment]
En fait les autres clients ont deja la feature, donc on aura même pas besoin de faire ca. Closing.
