### ISSUE TITLE
Présence de la bannière d'upgrade

### ISSUE THREAD

**Issue by estellecomment** [dinsic-pim/riot-web#183]
Est-ce qu'on a bien une bannière sur le client "Une nouvelle version est disponible, mettre à jour" quand on change de version sur le serveur ?

Tester.

Epic : #180

**Comment by celiacheff** [comment]
Dans NewVersionBar, on s'attend à une version du style: [vectorversion]-react-[react-sdk-version]-js-[js-sdk-version], mais j'ai des 404 sur l'URL de version, je continue à chercher

**Comment by estellecomment** [comment]
Deploying 2.3.7 from branch `develop_build_tmp_2.3.7`
Deploying 2.4.0 from branch `v2.4.0-tchap-rc.1-branch` (can't deploy from tag in scalingo)

No upgrade banner. Investigating. We probably don't set the version numbers correctly.

**Comment by estellecomment** [comment]
Victoire ! Ca marche sur scalingo !
![image](https://user-images.githubusercontent.com/911434/156026288-ffdbb7c7-29a1-4831-963c-0a680002fb1f.png)

Ca ne marche pas en local, le GET localhost:8080/version repond 404.

Il faut mettre à jour les numeros de version dans les package.json.

**Comment by estellecomment** [comment]
En francais aussi : 
![image](https://user-images.githubusercontent.com/911434/156030059-3fa720f6-96fa-4d3b-9997-ae082494a782.png)
