### ISSUE TITLE
After a connexion, the login/register page is still show but the client is connected

### ISSUE THREAD

**Issue by jdauphant** [dinsic-pim/riot-web#184]
J'ouvre l'app web
- Je vois l'écran welcome avec connexion ou inscription
- Je me connecte
- L'écran de welcome réapparait sans autre feedback
- Je raffraichi la page -> je suis bien connecté

Voici le haut des logs de la console juste avant de raffraichir
![image](https://user-images.githubusercontent.com/1238254/154732242-134da8b3-8c6e-4103-ab27-23fd74a34e2b.png)

**Comment by estellecomment** [comment]
In testing, I haven't seen this on Chrome or Firefox in macos, with external or internal users.

**Comment by estellecomment** [comment]
L'"écran de welcome" c'est bien ca @jdauphant : 

![image](https://user-images.githubusercontent.com/911434/157209825-1ef10082-1209-4e1c-bf27-dd2a3c0057e9.png)

On peut renommer "page de login/register" ? ("welcome" c'est plutot le modal  qui apparait apres que tu sois connecté)

**Comment by jdauphant** [comment]
Yes it's that

**Comment by estellecomment** [comment]
Not seen again during testing. If it does happen, it's confusing but doesn't break auth. So we're not fixing for now in 2.4.0.
