### ISSUE TITLE
[Bug] Registration broken - Nothing appears after a click on "S'inscrire"

### ISSUE THREAD

**Issue by Claire1817** [dinsic-pim/riot-web#186]
If the password doesn't contains all the mandatory special characters, there is no reaction when we click on the button "s'inscrire".
Navigator: Google Chrome
Tchap version: V2.4.0
<img width="866" alt="Capture d’écran 2022-02-22 à 10 46 20" src="https://user-images.githubusercontent.com/15031750/155116464-a03c626c-09da-4f1f-ac92-8aacc89e2c9e.png">

**Comment by estellecomment** [comment]
This happens for agent users, external users, and for valid passwords.

**Comment by estellecomment** [comment]
![image](https://user-images.githubusercontent.com/911434/155357832-b785127e-a9d1-4c51-8af7-13fa1a7ea00a.png)

**Comment by celiacheff** [comment]
Response from server with the flow: `{"session":"JgbpFIXaKVgvmpNouOSQrSbo","flows":[{"stages":["m.login.email.identity"]}],"params":{}}` lauched by client url `/_matrix/client/r0/register`

**Comment by estellecomment** [comment]
Fixed by PR https://github.com/tchapgouv/matrix-react-sdk/pull/387
