### ISSUE TITLE
[ Profile Details ] Picture isn't displayed correctly

### ISSUE THREAD

**Issue by Claire1817** [dinsic-pim/riot-web#191]
When we had clicked in an avatar the room details appear on the right and the picture isn't displayed correctly.
<img width="866" alt="Capture d’écran 2022-02-22 à 15 36 00" src="https://user-images.githubusercontent.com/15031750/155154819-693155f4-9895-423c-af84-029aac281a60.png">

**Comment by estellecomment** [comment]
Already present in 2.3.7
