### ISSUE TITLE
In a room, the actions for a user have changed

### ISSUE THREAD

**Issue by estellecomment** [dinsic-pim/riot-web#194]
Dans un salon privé, quand on selectionne un utilisateur, on voit ces options dans la sidebar de droite :

Dans 2.3.7 :
![image](https://user-images.githubusercontent.com/911434/155177840-a7ded0b3-b6e1-44da-9171-1d239ffe9347.png)

Dans 2.4.0 :
![image](https://user-images.githubusercontent.com/911434/155177350-0d92b011-815e-4617-b239-30c40c68771b.png)

"Inviter" n'a pas trop de sens puisque l'utilisateur est deja dans le salon.
"Envoyer un message" dirige vers les DM avec cet utilisateur.

**Comment by estellecomment** [comment]
This is breaking for external users : they have no other way to start a conversation with a user, since they cannot search for users. So they need the "Envoyer un message" link.

**Comment by estellecomment** [comment]
This is apparently voluntary for external users. So does not break a feature.

**Comment by celiacheff** [comment]
So what should we have here ? :)

**Comment by estellecomment** [comment]
"Envoyer un message".
@giomfo is it required that we block external users from sending messages to users that are already in their channel ? It's easier to allow "Envoyer un message" for everyone.

**Comment by giomfo** [comment]
> "Envoyer un message". @giomfo is it required that we block external users from sending messages to users that are already in their channel ? It's easier to allow "Envoyer un message" for everyone.

You may keep displaying the option even for the external account. They will observe an error when they will use it, but this may be ok for v2.4.0
It would be good to consider it differently in v4

Did you understand why the option "inviter" was displayed ? I don't know what does that mean here?
