### ISSUE TITLE
Attached files : download link does not display

### ISSUE THREAD

**Issue by estellecomment** [dinsic-pim/riot-web#196]
When uploading a file (e.g. pdf, docx), once you have decrypted the file, the message is empty, and the download is impossible : 

![image](https://user-images.githubusercontent.com/911434/155336465-06c06543-4bd3-4042-b774-e69e6b8ed8e2.png)

Expected : a download link :

![image](https://user-images.githubusercontent.com/911434/155336542-ba22f084-7c00-4510-a040-f81764fdc961.png)

**Comment by celiacheff** [comment]
Je pense que c'est pas testable en dev. Dans l'IFrame je trouve ça, et ça vient du serveur:
`    if (e.origin === "https://www.tchap.gouv.fr" || e.origin === "https://tchap.gouv.fr" || e.origin === "https://www.beta.tchap.gouv.fr") eval("("+e.data.code+")")(e);`
Des explications sont fournies dans le react-sdk `src/components/views/messages/MFileBody.js`, l68-127

**Comment by estellecomment** [comment]
Element code that does this : https://github.com/matrix-org/usercontent/blob/master/v1.html
Tchap's code looks different, so we probably forked it

**Comment by estellecomment** [comment]
Tchap's version : https://github.com/matrix-org/matrix-dinsic/blob/b1bbf4cd95a660980aa4bcc383b5cf7c077ffaba/ansible/roles/matrix-apache-dinsic/files/dinsic-chat/v1.html#L18

**Comment by estellecomment** [comment]
Fix deployed for dinum. 
Now deploy on other servers.

**Comment by estellecomment** [comment]
Deployed on all servers, tested on rc3.
