### ISSUE TITLE
<code> font does not display numbers

### ISSUE THREAD

**Issue by estellecomment** [dinsic-pim/riot-web#201]
On OSX, chrome : 

`<code>0123456789 ABCDE !@#$%^&amp;*()_+{}[]</code>`

displays as :

![image](https://user-images.githubusercontent.com/911434/155990298-2c4a444a-36cc-4f8a-b7fd-db63af7ce030.png)

This is a problem for displaying device keys in Settings > Security and Privacy. Copy-pasting still works properly though.

**Comment by celiacheff** [comment]
No problems for me on Manjaro (FF and Chromium). Might be a font bug, can you try with another font maybe ?

**Comment by estellecomment** [comment]
Not present in 2.3.7

**Comment by estellecomment** [comment]
Present in 2.4.0 on OSX on firefox as well

**Comment by estellecomment** [comment]
Present on windows 10 pro, on Chrome, Firefox and Edge

**Comment by estellecomment** [comment]
Not present on Ubuntu on Firefox. The font used is Noto.

**Comment by celiacheff** [comment]
I think the default font was changed in Element, since it had problems, but maybe this one had problems at this point of time

**Comment by estellecomment** [comment]
We have this line in theme-tchap.css (copied from element's theme-light.css and theme-dark.css) : 
```
pre, code {
    font-family: Inconsolata, Twemoji, 'Apple Color Emoji', 'Segoe UI Emoji', 'Noto Color Emoji', Courier, monospace;
    font-size: 100% !important;
}
```
It looks like inconsolata is not displaying numbers, so Twemoji is displaying them, and Twemoji displays them as squares.
Not clear to me why inconsolata is not displaying the numbers.

**Comment by Pascal-aa** [comment]
On the same computer, this bug is :
- **Present** on 2.4.0 on Firefox 91.3.0esr (64 bits)
- **Not present** on 2.3.7 on Edge 101.0.1210.47 (64 bits)

This bug seems to come with version 2.4.0

**Comment by jdauphant** [comment]
This PR could be the fix https://github.com/matrix-org/matrix-react-sdk/pull/3008/files

**Comment by jdauphant** [comment]
I have made the fix in a PR.
