### ISSUE TITLE
Tagging users displays wrong (disappears partially)

### ISSUE THREAD

**Issue by estellecomment** [dinsic-pim/riot-web#222]
Present in 2.4.0 rc3
Not present in 2.3.7 

 - 1 : Try to tag Estelle by typing "@est", a selection appears

![image](https://user-images.githubusercontent.com/911434/157422557-ed72ed18-d757-42c6-90de-69a37bb7330c.png)

 - 2 : click on the user in the section : the tag appears empty in the text bar : 

Got empty tag : 
![image](https://user-images.githubusercontent.com/911434/157422763-0cbbaa60-b9ec-40e1-b24b-3b0e7f330eac.png)

Expected visible tag : 
![image](https://user-images.githubusercontent.com/911434/157422919-969adc7b-dbd0-4e0e-aff5-3d2cd8c2d67c.png)

 - 3 : press enter. You should see the tag in the sent message.

Got non-styled tag : 
![image](https://user-images.githubusercontent.com/911434/157423151-c18d296e-ddd8-401c-bd6d-e84ec285c535.png)
 
Expected styled tag : 
![image](https://user-images.githubusercontent.com/911434/157423171-1df5f5cd-fddb-4241-9334-ac50b4b5bade.png)

**Comment by est** [comment]
hey don't tag the wrong github user in a "taggong user wrong" issue 🤣

**Comment by estellecomment** [comment]
Hahaha sorry about that :D

**Comment by estellecomment** [comment]
Maybe a merge problem in MessageComposerInput.js, `renderNode`, `case 'pill'` ?
In prod, you can see `class="mx_Pill mx_UserPill mx_UserPill_selected"` on the generated tag of the user, in the editor.

But I don't see any changes there since 2.3.7 : https://github.com/tchapgouv/matrix-react-sdk/compare/v2.3.7-tchap...2.4.0-tchap-rc.3
