### ISSUE TITLE
Deploy 2.4.0 to production

### ISSUE THREAD

**Issue by odelcroi** [dinsic-pim/riot-web#244]
- update documentation on release process
- prepare q&a process for next minor version (2.5.0)

# 2.4.0 status
- [x] Tag : https://github.com/tchapgouv/tchap-web/tree/v2.4.0-tchap
- [x] Deploy to beta : https://www.tchap.gouv.fr/beta
- [x]  Go/NoGo deadline : 
- [x]  Deploy to production at 20%
- [x]  Deploy to production at 100%

**Comment by jdauphant** [comment]
Done
