### ISSUE TITLE
MIssing translation : "edited" in english

### ISSUE THREAD

**Issue by estellecomment** [dinsic-pim/riot-web#250]
In 2.4.0, in english, when displaying an edited message :
![image](https://user-images.githubusercontent.com/911434/168032258-30618947-dd95-466a-92df-875cf2816730.png)

Don't know if it's present in 2.3.7

**Comment by estellecomment** [comment]
Also when hovering over reactions : 
![Screen Shot 2022-05-13 at 09 55 47](https://user-images.githubusercontent.com/911434/168237926-9b53cf07-dfba-46da-89ce-318feaa0d8ba.png)

**Comment by jdauphant** [comment]
Duplicate #247

**Comment by celiacheff** [comment]
Solved in https://github.com/tchapgouv/tchap-web/pull/264
