### ISSUE TITLE
Images qui n'apparaissent pas dans le Forum Humour en tout genre :((

### ISSUE THREAD

**Issue by JDixmier** [dinsic-pim/riot-web#267]
![Untitled](https://user-images.githubusercontent.com/1238254/171645575-94042462-c294-45a4-a368-6c58290e7677.png)

Ce qui se passe quand je cherche à atteindre une des URL : 

![Capture d’écran 2022-06-01 à 17 09 29](https://user-images.githubusercontent.com/45665538/171438313-992cc2de-b220-4ef3-a036-ddfaa290cb25.png)

Dans mon cas : pb constaté sur Chrome Version 101.0.4951.41 (Build officiel) (x86_64)
Des utilisateurs l'ont rapporté sur Edge

Le pb semble se poser notamment sur les Forum mais pas tous

**Comment by jdauphant** [comment]
C'est peut être fix avec #260 sinon c'est un doublon de #265

**Comment by jdauphant** [comment]
Il faut regardé quel client a envoyé l'image

**Comment by jdauphant** [comment]
c'est bien un doublon de #265
