### ISSUE TITLE
Missing translation in both languages : "An email has been sent"

### ISSUE THREAD

**Issue by estellecomment** [dinsic-pim/riot-web#274]
![Screen Shot 2022-06-14 at 11 40 46](https://user-images.githubusercontent.com/911434/173547656-33ddf8f2-886c-4c2e-8c00-b02de98774eb.png)
![Screen Shot 2022-06-14 at 11 41 20](https://user-images.githubusercontent.com/911434/173547684-88745f10-0bb7-4e96-a625-061864045852.png)

When creating an account for an external user.
Seen on beta.tchap.gouv.fr, v2.5.3 
(Not checked if present on other versions)

**Comment by JDixmier** [comment]
Not only for external users : 

<img width="458" alt="56e5b40d7b5623815a1fecc79150b8366231f838" src="https://user-images.githubusercontent.com/45665538/176402326-3bd166ed-2b80-4503-b495-c3ebef65dbfd.png">

**Comment by estellecomment** [comment]
PR faite, j'ai demandé une review à @JDixmier et @celiacheff : https://github.com/tchapgouv/tchap-web/pull/282
