### ISSUE TITLE
'device_keys' values must be a list of strings (mainlining)

### ISSUE THREAD

**Issue by guillaumevillemont** [dinsic-pim/riot-web#275]
## Context 
I'm currently deploying synapse v1.59.1 (from v1.31 currently) which is a big step with some changes in the API.

## What happened
On dev env, when I try to send a message (federation or not) I see this error in tchap-web (v2.5.3) : 
![image](https://user-images.githubusercontent.com/88834548/173849163-c4bfdb4d-0ae8-49ca-a953-d6471e8042f3.png)

Corresponding to the query `POST /_matrix/client/r0/keys/query`
payload is : 
```
{
    "device_keys": {
        "@guillaume.villemonttest1-matrix.org:agent1.tchap.incubateur.net": {},
        "@guillaume.villemonttest2-matrix.org:agent1.tchap.incubateur.net": {},
        "@guillaumevtest2-element.io:agent2.tchap.incubateur.net": {},
        "@guillaumevtest1-element.io:agent2.tchap.incubateur.net": {}
    },
    "token": "s1284_1_10_242_569_1_422_540_1"
}
```
**to reproduce : connect to agent1 which is the only HS with the updated synapse**

## Expected
Message should be sent.
I can't reproduced using Element-web, payload was : 
```
{
    "device_keys": {
        "@guillaumevtest1-element.io:agent2.tchap.incubateur.net": []
    },
    "token": "s1300_1_20_246_580_1_435_557_1"
}
```

Synapse introduced a [validation in v 1.42](https://github.com/matrix-org/synapse/commit/ee3b2ac59a5645cb213b3c11c473613b80fe1e0f)
The endpoint spec documentation : https://spec.matrix.org/v1.2/client-server-api/#post_matrixclientv3keysquery

**Comment by jdauphant** [comment]
@estellecomment @babolivier @mcalinghee @celiacheff  can we deploy a Tchap V4 in this env to check the compatibility ?

**Comment by jdauphant** [comment]
We may need to patch Tchap Web v2.4 if there it's not compatible with mainline

**Comment by estellecomment** [comment]
Deployed v4 with dev env, url shared in tchap channel.
