### ISSUE TITLE
New endpoints - Mainlining

### ISSUE THREAD

**Issue by guillaumevillemont** [dinsic-pim/riot-web#283]
Doing some tests on Dev env (mainlined synapse), I got some weird issues which are related to changing endpoints.
From mainlining documentation : 

*The endpoints changing are:
/_matrix/client/unstable/users/info -> /_matrix/client/v1/account_status
The new request format is described in [MSC3720](https://github.com/matrix-org/matrix-spec-proposals/pull/3720)
In addition to the MSC, the endpoint also returns an org.matrix.expired field for each user (if the user exists) that indicates whether the user is expired
/_matrix/client/unstable/account_validity/\* -> /_synapse/client/email_account_validity/\*
The request format does not change
/_synapse/admin/v1/account_validity/validity -> /_synapse/client/email_account_validity/admin
The request format does not change
Not sure if used directly by clients
/_matrix/client/unstable/account/3pid/lookup (and equivalent bulk_lookup)
Replaced with v2 identity API (see [the Matrix specification](https://spec.matrix.org/latest/identity-service-api/) for more details)
/_matrix/client/versions
No change in the route
m.lazy_load_members should not be relied on to figure out whether the homeserver supports lazy-loading. The mention of r0.5.0 or more recent versions of the Matrix specification in the response must be used instead.*
**source**:  https://docs.google.com/document/d/1vzjZgauLAMvsjVUdxLnqYkqf2GHKZcQupooEVutfmVA/edit?pli=1#heading=h.hl9xdcqvj2py

**Comment by guillaumevillemont** [comment]
FTR, the error I faced was a bug in mainlined synapse. But issue is still relevant when we will move out from "mainlined" (with backported route) and go 100% upstream.
I'll keep it open, but this is just Not urgent (yet).

**Comment by mcalinghee** [comment]
I am going to close this issue : we have reported the API changes and moved them into individual issues.
Those issues have been grouped in and will be addressed separately : 
- https://github.com/tchapgouv/tchap-web/issues/292
