### ISSUE TITLE
Backport "correct request body for the /keys/query endpoint" to support 

### ISSUE THREAD

**Issue by jdauphant** [dinsic-pim/riot-web#285]
The last version of synapse enforce the "/keys/query endpoint" API.
We need to backport : https://github.com/matrix-org/matrix-js-sdk/pull/1307 in matrix-js-sdk

**Comment by estellecomment** [comment]
From what I can tell, our js-sdk is based on element's v2.2.0. The PR we have to backport got addded to v5.3.0. It's too far forward for us to merge our js-sdk with element's v5.3.0.

**Comment by jdauphant** [comment]
I have done more than the backport. I have checked the code where this api call is made. They was just a transformation from JS to TS.
The more trouble was to adapte the tests.

**Comment by mcalinghee** [comment]
Duplicate with #275
