### ISSUE TITLE
[Investigation] API change : /account/3pid/lookup

### ISSUE THREAD

**Issue by mcalinghee** [dinsic-pim/riot-web#293]
/_matrix/client/unstable/account/3pid/lookup (and equivalent bulk_lookup) → v2 identity
- le process est peu plus compliqué, si j’ai bien compris il faut:
    - 2 possibilités, avec ou sans hash ☘️
    - récupérer le pepper depuis /hash_details
    - sha-256 '<address> <medium> <pepper>' puis b64
    - Passer au /lookup le(s) hash (c’est une liste maintenant), l’algo utilisé, le pepper
    - Récupérer la liste de mapping hash↔email
    - [https://spec.matrix.org/v1.3/identity-service-api/#post_matrixidentityv2lookup](https://spec.matrix.org/v1.3/identity-service-api/#post_matrixidentityv2lookup)

**Comment by celiacheff** [comment]
Note: il sera peut-être plus efficace de cherry-picker le code du repo Matrix js-sdk:
Le code commence ici: https://github.com/matrix-org/matrix-js-sdk/blob/ae9bb6f27f20b93f21be0aec51b69f774779504c/src/client.ts#L8496

**Comment by mcalinghee** [comment]
When searching a new contact on Tchap - Direct Message, we have an error a Bad Request: https://matrix.agent1.tchap.incubateur.net/_matrix/client/unstable/account/3pid/lookup?medium=email&address=recarghgxvxxtlutab@kvhrr.com&id_server=matrix.agent1.tchap.incubateur.net

Error when searching a contact:
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/3725676/180797270-8c4ac8e0-3e83-4525-959d-75fdc676938e.png">

@guillaumevillemont : we think we have an error in the backend as we did not change the endpoint in our code

**Comment by jdauphant** [comment]
Also this feature may not needed, the server will manage the email invitation (to be checked)

**Comment by celiacheff** [comment]
Not sure about, that, there is a call to 3pid before the user is invited to chat, I checked and didn't got the email (RoomInvite.js l184)

**Comment by guillaumevillemont** [comment]
Mitigated by https://github.com/vector-im/synapse-tchap/commit/1a73c4bbbd96147528751a65ac4812e649879950
This fix the contact search regression on tchap-web v2.

**Comment by mcalinghee** [comment]
At this moment, the mainlining is a transition version meaning the former APIs and newer APIs are available.
No need to adapt tchap-web-v2 on the new API yet.
A fix was provided on the mainlining in order to fix the /lookup endpoint and make it work as it was before
