### ISSUE TITLE
[Investigation] Bug : Preview

### ISSUE THREAD

**Issue by mcalinghee** [dinsic-pim/riot-web#295]
The Preview feature is now available 
When joining a new room, we have a preview with this window : 
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/3725676/180970921-f65b7a9d-a528-4fc8-b6cb-0eb9811d1ded.png">

**Question**
1/ Do we need this feature?
2/ If not, we need to find a way to de-activate it

**Comment by celiacheff** [comment]
Les previews doivent être désactivées dans Tchap. Je m'occupe de ça

**Comment by celiacheff** [comment]
Ok, mauvais call de ma part, c'est pas un problème. Du coup, j'ai retesté les comportements attendus (avec comptes externes) et c'est ok. Je close
