### ISSUE TITLE
Bug: publicised groups - Error : Cannot display flair

### ISSUE THREAD

**Issue by mcalinghee** [dinsic-pim/riot-web#297]
Au démarrage
```
POST https://matrix.agent1.tchap.incubateur.net/_matrix/client/r0/publicised_groups
400 (Bad Request) {"errcode":"M_UNRECOGNIZED","error":"Unrecognized request"}
Cannot display flair, server does not support groups
```

- The Flair feature has been removed in new version : https://github.com/matrix-org/matrix-react-sdk/pull/8027

- _Flair is a series of badges after the user’s (disambiguated) display name._
More information are described here : https://github.com/vector-im/riot-meta/issues/118

**Action**
We could removed this code in order to disable this feature

**Comment by celiacheff** [comment]
Apparemment, la notion de groupes part aussi avec les flairs, https://github.com/matrix-org/matrix-spec-proposals/issues/1214.
Y'a bcp d'intégrations groups/flairs, je propose de tout virer.
Question au passage, est-ce qu'on efface, ou on commente ?
