### ISSUE TITLE
Mainlining will maybe introduce a spinner bug in v2

### ISSUE THREAD

**Issue by estellecomment** [dinsic-pim/riot-web#323]
There was a bug in old versions of android and ios with mainlined element synapse, where an infinite spinner appeared, when you scrolled to the start of a room containing messages, or when you created a room. 
It doesn't happen every time so it's a bit hard to reproduce...

Maybe this could appear in tchap-web v2. Or not.

**Comment by weeman1337** [comment]
[This is the PR](https://github.com/matrix-org/synapse/pull/12903) for the spec fix in synapse.

**Comment by giomfo** [comment]
@estellecomment I don't think the web client was exposed to this issue
It has been fixed on Element iOS and Android in June 2022, we can see the PR attached to the synapse [PR](https://github.com/matrix-org/synapse/pull/12903)
I don't see any PR related to Element-web, but if a fix has been done, it was done at the same period.

Can you please confirm the current version of Tchap-web deployed on Production is based on a recent Element-web ?
In that case you can close this issue
