### ISSUE TITLE
Correct the "erreur d'intégration"

### ISSUE THREAD

**Issue by elsa-ssg** [dinsic-pim/riot-web#45]
On Tchap web **v2**

There are 4 squares with a red one and when it's pointed with the mouse, it appears "integration error"

![image](https://user-images.githubusercontent.com/48802291/60731990-2e50ff80-9f49-11e9-8d88-b56cb740d4e6.png)

**Comment by Yoshiin** [comment]
Since we don't support plugin, can I hide this button @jp-modernisation-gouv-fr ?

**Comment by giomfo** [comment]
@Yoshiin yes you should hide this button for the moment

**Comment by Yoshiin** [comment]
Done.
