### ISSUE TITLE
add the FAQ link next to the marianne

### ISSUE THREAD

**Issue by elsa-ssg** [dinsic-pim/riot-web#46]
On Tchap web **v2**

Since there is no more homepage, the link to the FAQ has been deleted.
If the FAQ button is placed next to the Marianne, it will be clearly visible

**Comment by Yoshiin** [comment]
I can do it. 
But FAQ & CGU are already present in "Settings" > "Help & About" (the link is presently pointing to riot.im but I will change it).
Do you really want to me to add it ? I can add GCU & user guide link too if you want.
Do you agree wit something like that : 
![faq_link](https://user-images.githubusercontent.com/2992581/60794066-35eeef00-a169-11e9-99e0-5f4d00b9de1e.png)

**Comment by Yoshiin** [comment]
Done.
