### ISSUE TITLE
increase the contrast of the names of the members

### ISSUE THREAD

**Issue by elsa-ssg** [dinsic-pim/riot-web#47]
On Tchap-web **v2**

Make the names of the members in the list of the members on the right more contrasted because  it look like they are "shaded" like they are not in the group

**Comment by Yoshiin** [comment]
They are "shaded" because they are considered as "offline". Since Tchap doesn't have "presence" activated users are  greyed like that. It's possible to change it, but it's really what you want ? 
@jp-modernisation-gouv-fr What do you think ?

**Comment by Yoshiin** [comment]
Done.
