### ISSUE TITLE
disable 2 options by default

### ISSUE THREAD

**Issue by elsa-ssg** [dinsic-pim/riot-web#48]
On Tchap web **v2**

disable theses options by default :

-  "Afficher les messages d'arrivée et de départ (les invitations/expulsions/bannissements ne sont pas concernés)" 
- "Activer le panneau de filtrage de communauté"

**Comment by Yoshiin** [comment]
These two options are already disabled by default. 
Since they are linked to the account, if they have been activated one time (in the v1 or by useing the v2 in an earlier deployment) they will stay until you change them.
