### ISSUE TITLE
Manage a minimum version of the mobile clients

### ISSUE THREAD

**Issue by giomfo** [dinsic-pim/riot-web#78]
To manage a minimum version for the mobile Tchap clients (dinsic-pim/tchap-ios#214, dinsic-pim/tchap-android#493), we are working on 2 files "android-config" and "ios-config" that contain JSON data about the requirements on the client versions (we followed the example provided here: https://github.com/matrix-org/matrix-dinsic/issues/257#issuecomment-487056250)

I request by this issue to make them (when they will be ready) available from the Tchap Web client thanks to the following url:
"https://www.tchap.gouv.fr/client/config/android" -> "android-config"
"https://www.tchap.gouv.fr/client/config/ios" -> "ios-config"

**Comment by giomfo** [comment]
~@jp-modernisation-gouv-fr @Yoshiin : Do you think we should split this file in 2 (one by platform):
"android-app-version-config" and "apple-app-version-config"?~

**Comment by Yoshiin** [comment]
> @jp-modernisation-gouv-fr @Yoshiin : Do you think we should split this file in 2 (one by platform):
> "android-app-version-config" and "apple-app-version-config"?

Yes, I think we should.
Do I have to do the same on web client ?

**Comment by giomfo** [comment]
@Yoshiin  FYI I updated the description of this issue
@bmarty and I are still working on the files. We will post them here as soon as they will be ready

**Comment by giomfo** [comment]
@Yoshiin FYI I updated again the description of this issue

here are the 2 config files:
[android-config.txt](https://github.com/dinsic-pim/tchap-web/files/3820262/android-config.txt)
[ios-config.txt](https://github.com/dinsic-pim/tchap-web/files/3820263/ios-config.txt)

**Comment by Yoshiin** [comment]
@giomfo Done

**Comment by giomfo** [comment]
@Yoshiin we will need to change the file paths. Can you please move the config files to the following path:

"https://www.tchap.gouv.fr/client/config/agent/android" -> "android-config"
"https://www.tchap.gouv.fr/client/config/agent/ios" -> "ios-config"

**Comment by giomfo** [comment]
@Yoshiin can you please add a new config file to the following path:

"https://www.tchap.gouv.fr/client/config/secure/android" -> "secure_android-config"

[secure_android-config.txt](https://github.com/dinsic-pim/tchap-web/files/3824085/secure_android-config.txt)

**Comment by Yoshiin** [comment]
@giomfo Done

**Comment by giomfo** [comment]
thx

**Comment by giomfo** [comment]
@Yoshiin Hi, we will need to update the config file with the new ones:
[android-config.txt](https://github.com/dinsic-pim/tchap-web/files/3857948/android-config.txt)
[ios-config.txt](https://github.com/dinsic-pim/tchap-web/files/3857949/ios-config.txt)
[secure_android-config.txt](https://github.com/dinsic-pim/tchap-web/files/3857950/secure_android-config.txt)

And create 2 new paths:
"https://www.tchap.gouv.fr/client/config/preprod/android" -> "android-config"
"https://www.tchap.gouv.fr/client/config/preprod/ios" -> "ios-config"

**Comment by Yoshiin** [comment]
Done.
FYI all config files must be in .json extension.

**Comment by giomfo** [comment]
👍
