### ISSUE TITLE
Design : Make a bubble view for rooms

### ISSUE THREAD

**Issue by Yoshiin** [dinsic-pim/riot-web#87]
Make a bubble view for rooms.
Waiting for designers to show a possible design.

Here is an exemple from messenger.com
![messenger_design](https://user-images.githubusercontent.com/2992581/69526683-0c453180-0f6b-11ea-821a-c276d69a6dc8.png)

And one from whatsapp web:
![whatsapp_design](https://user-images.githubusercontent.com/2992581/69527012-b1f8a080-0f6b-11ea-9884-3a65662f15c9.png)

**Comment by jdauphant** [comment]
Element will implement Bubble
