### ISSUE TITLE
Some administrators cannot invite users while other administrators can

### ISSUE THREAD

**Issue by elsa-ssg** [dinsic-pim/riot-web#90]
In a private room, some administrators are able to invite users but some users cannot, an error message appears instead. 
When using the Android application, it works normally.

![errorinviteusers](https://user-images.githubusercontent.com/48802291/71981038-cf36b500-3221-11ea-826b-99363da9bb0e.JPG)

Versions
Version de matrix-react-sdk : 2.0.5
Version de tchap-web : 2.0.5
version de olm : 3.0.0

On Firefox 52

**Comment by Yoshiin** [comment]
More informations are needed. Frequency, how to reproduce,...
