### ISSUE TITLE
Undefined room state: last read marker bar won't go away, and the user fails to send new message

### ISSUE THREAD

**Issue by giomfo** [dinsic-pim/riot-web#92]
Description provided by a Tchap user:
Voilà quelques détails sur le bug que je rencontre. Deux salons sont maintenant concernés. Quand je clique sur le salon, j'arrive au niveau des derniers messages non-lus (jusque là, le comportement est normal). Le bug vient quand je descends dans la conversation pour lire les messages plus récents. En effet, les derniers messages restent non lus. Et on peut aussi noter que, pour les messages anciens, j'ai accès aux options des messages. Mais impossible d'ouvrir le popup avec les messages restant marqués non lus. Rien ne se fait quand on clique sur la bulle avec les 3 points. Pour résumer, c'est comme si le salon s'était figé pour moi à un instant t. En revanche, les nouveaux messages continuent d'arriver.

**Comment by Yoshiin** [comment]
It looks like this error comes from some undefined users inside a Pill (quote).
