### ISSUE TITLE
After clicking on closing my account, the window stays frozen instead of disappearing

### ISSUE THREAD

**Issue by clemhacks** [dinsic-pim/riot-web#95]
![Capture fermer le compte tchap bug (2)_LI](https://user-images.githubusercontent.com/61703515/78041661-42f3e400-7371-11ea-86fd-194a7167f4ee.jpg)

**Comment by Yoshiin** [comment]
This is the Riot web client behavior too.
I tried to do fix it, but nothing really working.
Not a priority, will see later.
